
workflows:
  android-build:
    name: Android Build
    environment:
      flutter: "3.3.10"
      vars:
        PACKAGE_NAME: "com.kitchencare.app"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
